project_id = "ktzfovzwayfqczytmhno"

[functions.get-ticket-messages]
verify_jwt = true

[functions.notify-ticket]
verify_jwt = false

[functions.create-mercadopago-payment]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.monday-webhook]
verify_jwt = false

[functions.migrate-attachments]
verify_jwt = false

[functions.create-cleaner]
verify_jwt = true